export class Texts {
  static blog = '📝Blog'
  static tags = '🏷️Tags'
  static projects = '🛠️Proyectos'
  static aboutme = '👤Sobre mí'
  static posts = '📰 Posts'
  static readmore = '🔍 Leer más'
  static previousPost = '⬅️ Post anterior'
  static nextPost = '➡️ Post siguiente'
  static backToBlog = '🏠 Volver al blog'
  static previous = '🔙 Anterior'
  static next = '🔜 Siguiente'
  static allPosts = '📚 Todos los Posts'
  static publishedOn = '📆 Publicado el'
  static outOf = 'de'
  static loadComments = '🔄 Cargar comentarios...'
  static lastPosts = '📰 Últimos posts'
}
